# Database information
db_user: root
db_pass: root
db_db: segments_tester
db_test_db: segments_1234

# This table should have two attributes, query and solution.
# Mispelled should be what we send to the engines
# Solution should be what they should return (in a perfect world)
# This will also be used as the prefix for other tables, such at 3grams
queries_table: queries

# If segments is below this threashold, we'll consider using the 3grams results
confidence_threashold: 0.2

# If a candidates edit distance is >= to this, it will be removed from ten candidates list
# i.e. it will be disreguarded if its value is too high.
edit_distance_prune_at: 5


# This is just using by rspec testing
# to verify the yaml is all good
# i.e.  Ignore and don't change this
rspec_test_var: true